<a href="https://colab.research.google.com/github/vtu28901-gif/10215CS180---SS-26-27---Synthetic-Data-generation-using-Generative-AI/blob/main/Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Part A — LOAD THE DATA**

In [2]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
df=pd.read_csv("/content/drive/MyDrive/glixify_dataset.csv")

In [5]:
df.head()  #This is important because later you generate approximately the same number of synthetic rows.

,participant_id,timestamp,glucose_mg_dl,heart_rate_bpm,hrv_ms,spo2_percent,sleep_duration_hours,activity_level,steps,sleep_quality,device_type
0,P063,08-01-2026 04:00,107.840082,65.454512,54.239094,96.017807,5.500982,Low,252.0,Fair,Wearable_A
1,P047,08-01-2026 12:00,105.758855,63.699755,48.234028,95.728198,NaN,Low,37.0,NaN,Wearable_A
2,P018,22-01-2026 07:00,97.844208,74.428713,51.861775,97.958764,NaN,Moderate,1209.0,NaN,Wearable_C
3,P048,09-01-2026 18:00,112.451573,66.269009,39.164509,97.602378,NaN,Low,527.0,NaN,Wearable_A
4,P046,14-01-2026 21:00,121.005022,66.406237,48.133023,98.483996,NaN,Moderate,1246.0,NaN,Wearable_B

In [6]:
df.shape

(10000, 11)

In [7]:
df.columns #learning the schema of the dataset

Index(['participant_id', 'timestamp', 'glucose_mg_dl', 'heart_rate_bpm',
       'hrv_ms', 'spo2_percent', 'sleep_duration_hours', 'activity_level',
       'steps', 'sleep_quality', 'device_type'],
      dtype='object')

In [8]:
df.head()

,participant_id,timestamp,glucose_mg_dl,heart_rate_bpm,hrv_ms,spo2_percent,sleep_duration_hours,activity_level,steps,sleep_quality,device_type
0,P063,08-01-2026 04:00,107.840082,65.454512,54.239094,96.017807,5.500982,Low,252.0,Fair,Wearable_A
1,P047,08-01-2026 12:00,105.758855,63.699755,48.234028,95.728198,NaN,Low,37.0,NaN,Wearable_A
2,P018,22-01-2026 07:00,97.844208,74.428713,51.861775,97.958764,NaN,Moderate,1209.0,NaN,Wearable_C
3,P048,09-01-2026 18:00,112.451573,66.269009,39.164509,97.602378,NaN,Low,527.0,NaN,Wearable_A
4,P046,14-01-2026 21:00,121.005022,66.406237,48.133023,98.483996,NaN,Moderate,1246.0,NaN,Wearable_B

In [9]:
df.info() #You need this before modeling because a model must know what type of data it is dealing with.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   participant_id        10000 non-null  object
 1   timestamp             10000 non-null  object
 2   glucose_mg_dl         9719 non-null   float64
 3   heart_rate_bpm        10000 non-null  float64
 4   hrv_ms                9797 non-null   float64
 5   spo2_percent          9869 non-null   float64
 6   sleep_duration_hours  3200 non-null   float64
 7   activity_level        10000 non-null  object
 8   steps                 9665 non-null   float64
 9   sleep_quality         3200 non-null   object
 10  device_type           10000 non-null  object
dtypes: float64(6), object(5)
memory usage: 859.5+ KB

In [10]:
df["timestamp"].head(20)

0     08-01-2026 04:00
1     08-01-2026 12:00
2     22-01-2026 07:00
3     09-01-2026 18:00
4     14-01-2026 21:00
5     25-01-2026 16:00
6     09-01-2026 04:00
7     18-01-2026 02:00
8     26-01-2026 15:00
9     21-01-2026 15:00
10    09-01-2026 02:00
11    14-01-2026 15:00
12    21-01-2026 00:00
13    13-01-2026 05:00
14    20-01-2026 03:00
15    06-01-2026 09:00
16    09-01-2026 10:00
17    08-01-2026 06:00
18    25-01-2026 03:00
19    22-01-2026 10:00
Name: timestamp, dtype: object

In [11]:
df["timestamp"].dtype

dtype('O')

In [12]:
df["timestamp"].unique()[:20]

array(['08-01-2026 04:00', '08-01-2026 12:00', '22-01-2026 07:00',
       '09-01-2026 18:00', '14-01-2026 21:00', '25-01-2026 16:00',
       '09-01-2026 04:00', '18-01-2026 02:00', '26-01-2026 15:00',
       '21-01-2026 15:00', '09-01-2026 02:00', '14-01-2026 15:00',
       '21-01-2026 00:00', '13-01-2026 05:00', '20-01-2026 03:00',
       '06-01-2026 09:00', '09-01-2026 10:00', '08-01-2026 06:00',
       '25-01-2026 03:00', '22-01-2026 10:00'], dtype=object)

# ***Part B — UNDERSTAND DATA TYPES ***

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   participant_id        10000 non-null  object
 1   timestamp             10000 non-null  object
 2   glucose_mg_dl         9719 non-null   float64
 3   heart_rate_bpm        10000 non-null  float64
 4   hrv_ms                9797 non-null   float64
 5   spo2_percent          9869 non-null   float64
 6   sleep_duration_hours  3200 non-null   float64
 7   activity_level        10000 non-null  object
 8   steps                 9665 non-null   float64
 9   sleep_quality         3200 non-null   object
 10  device_type           10000 non-null  object
dtypes: float64(6), object(5)
memory usage: 859.5+ KB

# **Part C — Check Missing Values**

In [14]:
df.isnull().sum()

participant_id             0
timestamp                  0
glucose_mg_dl            281
heart_rate_bpm             0
hrv_ms                   203
spo2_percent             131
sleep_duration_hours    6800
activity_level             0
steps                    335
sleep_quality           6800
device_type                0
dtype: int64

In [15]:
df.isnull().mean() * 100

participant_id           0.00
timestamp                0.00
glucose_mg_dl            2.81
heart_rate_bpm           0.00
hrv_ms                   2.03
spo2_percent             1.31
sleep_duration_hours    68.00
activity_level           0.00
steps                    3.35
sleep_quality           68.00
device_type              0.00
dtype: float64

In [16]:
missing = df.isnull().sum()

missing[missing > 0]

glucose_mg_dl            281
hrv_ms                   203
spo2_percent             131
sleep_duration_hours    6800
steps                    335
sleep_quality           6800
dtype: int64

In [17]:
df[["sleep_duration_hours", "sleep_quality"]].isnull().sum()  #Check whether missing sleep values occur together

sleep_duration_hours    6800
sleep_quality           6800
dtype: int64

In [18]:
df[["sleep_duration_hours", "sleep_quality"]].isnull().all(axis=1).sum() #How many rows have both sleep duration AND sleep quality missing?

np.int64(6800)

In [19]:
df[["sleep_duration_hours", "sleep_quality"]].notnull().all(axis=1).sum() #How many rows have both sleep measurements present?

np.int64(3200)

In [20]:
df.groupby("activity_level")[
    ["sleep_duration_hours", "sleep_quality"]
].apply(lambda x: x.notnull().mean() * 100) #Check whether sleep availability relates to activity          #This is profiling

                sleep_duration_hours  sleep_quality
activity_level
High                        7.377980       7.377980
Low                        48.900052      48.900052
Moderate                    9.324567       9.324567

# *Part D — Numerical* *Profile* **bold text**

In [21]:
df.describe()

,glucose_mg_dl,heart_rate_bpm,hrv_ms,spo2_percent,sleep_duration_hours,steps
count,9719.000000,10000.000000,9797.000000,9869.000000,3200.000000,9665.000000
mean,106.251486,72.727045,46.052792,97.020902,6.813300,894.711433
std,13.794711,6.743651,8.858883,0.899899,0.698415,974.639706
min,65.000000,52.129685,15.669435,94.296831,4.313245,0.000000
25%,96.804580,67.850885,39.696226,96.369614,6.362490,223.000000
50%,105.772871,72.325500,45.958480,96.967141,6.810498,404.000000
75%,115.056572,77.341893,52.310568,97.623990,7.269670,1417.000000
max,159.905687,97.000467,73.870399,100.404306,9.255195,5773.000000

In [22]:
df["activity_level"].value_counts()

activity_level
Low         5773
Moderate    3346
High         881
Name: count, dtype: int64

In [23]:
df["activity_level"].value_counts(normalize=True) * 100

activity_level
Low         57.73
Moderate    33.46
High         8.81
Name: proportion, dtype: float64

In [24]:
df["sleep_quality"].value_counts()

sleep_quality
Good    1810
Fair    1027
Poor     363
Name: count, dtype: int64

In [25]:
df["device_type"].value_counts()

device_type
Wearable_A    4529
Wearable_B    3458
Wearable_C    2013
Name: count, dtype: int64

# **PART E-Exploring Relationships Between Variables**

In [26]:
baseline = df.sample(
    n=len(df),
    replace=True,                         #bootstrap resampling
    random_state=42
).reset_index(drop=True)

In [ ]:
df.groupby("activity_level")["heart_rate_bpm"].agg(
    ["count", "mean", "median", "std"]
).round(2)

                count   mean  median   std
activity_level
High              881  80.03   79.81  5.77
Low              5773  70.17   69.83  5.92
Moderate         3346  75.22   74.85  5.93

In [27]:
df.groupby("activity_level")["steps"].agg(
    ["count", "mean", "median"]
).round(2)

                count     mean  median
activity_level
High              851  3174.65  3174.0
Low              5594   254.27   252.0
Moderate         3220  1404.78  1405.0

# Part F — What should our synthetic data preserve?

In [28]:
baseline = df.sample(
    n=len(df),
    replace=True,                         #bootstrap resampling
    random_state=42
).reset_index(drop=True)

In [29]:
baseline.shape

(10000, 11)

In [30]:
numeric_cols = [
    "glucose_mg_dl",        #comparing numerical
    "heart_rate_bpm",
    "hrv_ms",
    "spo2_percent",
    "sleep_duration_hours",
    "steps"
]

comparison = pd.DataFrame({
    "real_mean": df[numeric_cols].mean(),
    "baseline_mean": baseline[numeric_cols].mean(),
    "real_std": df[numeric_cols].std(),
    "baseline_std": baseline[numeric_cols].std()
}).round(2)

comparison

                      real_mean  baseline_mean  real_std  baseline_std
glucose_mg_dl            106.25         106.29     13.79         13.79
heart_rate_bpm            72.73          72.63      6.74          6.79
hrv_ms                    46.05          46.11      8.86          8.83
spo2_percent              97.02          97.03      0.90          0.90
sleep_duration_hours       6.81           6.83      0.70          0.70
steps                    894.71         898.04    974.64        963.46

In [31]:
activity_compare = pd.DataFrame({
    "real_%": df["activity_level"].value_counts(normalize=True) * 100, #Compare categorical
    "baseline_%": baseline["activity_level"].value_counts(normalize=True) * 100
}).round(2)

activity_compare

                real_%  baseline_%
activity_level
Low              57.73       56.84
Moderate         33.46       34.63
High              8.81        8.53

In [32]:
real_corr = df[numeric_cols].corr()
baseline_corr = baseline[numeric_cols].corr()

corr_delta = baseline_corr - real_corr    #Compare relationships between baseline and real

corr_delta.round(2)

,glucose_mg_dl,heart_rate_bpm,hrv_ms,spo2_percent,sleep_duration_hours,steps
glucose_mg_dl,0.00,0.00,-0.00,-0.02,-0.03,0.00
heart_rate_bpm,0.00,0.00,-0.00,-0.01,0.00,0.01
hrv_ms,-0.00,-0.00,0.00,-0.00,0.00,0.01
spo2_percent,-0.02,-0.01,-0.00,0.00,-0.01,0.00
sleep_duration_hours,-0.03,0.00,0.00,-0.01,0.00,-0.01
steps,0.00,0.01,0.01,0.00,-0.01,0.00

# **DAY 2**

In [33]:
!pip install sdv

Collecting sdv
  Downloading sdv-1.38.5-py3-none-any.whl.metadata (14 kB)
Collecting boto3<2.0.0,>=1.28 (from sdv)
  Downloading boto3-1.43.111-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<2.0.0,>=1.31 (from sdv)
  Downloading botocore-1.43.111-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: cloudpickle>=2.1.0 in /usr/local/lib/python3.13/dist-packages (from sdv) (3.1.2)
Requirement already satisfied: graphviz>=0.13.2 in /usr/local/lib/python3.13/dist-packages (from sdv) (0.21)
Requirement already satisfied: numpy>=2.1.0 in /usr/local/lib/python3.13/dist-packages (from sdv) (2.1.3)
Requirement already satisfied: pandas<3,>=2.2.3 in /usr/local/lib/python3.13/dist-packages (from sdv) (2.2.3)
Requirement already satisfied: tqdm>=4.29 in /usr/local/lib/python3.13/dist-packages (from sdv) (4.67.3)
Collecting copulas>=0.12.1 (from sdv)
  Downloading copulas-0.14.1-py3-none-any.whl.metadata (9.7 kB)
Collecting ctgan>=0.11.1 (from sdv)
  Downloading ctgan-0.12.1-py3-none-any.whl.metadata (10 kB)
Collecting deepecho>=0.7.0 (from sdv)
  Downloading deepecho-0.8.1-py3-none-any.whl.metadata (11 kB)
Collecting rdt<2,>=1.18.2 (from sdv)
  Downloading rdt-1.22.0-py3-none-any.whl.metadata (11 kB)
Collecting sdmetrics>=0.32.0 (from sdv)
  Downloading sdmetrics-0.32.0-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: platformdirs>=4.0 in /usr/local/lib/python3.13/dist-packages (from sdv) (4.12.2)
Requirement already satisfied: pyyaml>=6.0.1 in /usr/local/lib/python3.13/dist-packages (from sdv) (6.0.3)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2.0.0,>=1.28->sdv)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.20.0,>=0.19.0 (from boto3<2.0.0,>=1.28->sdv)
  Downloading s3transfer-0.19.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.13/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.13/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.5.0)
Requirement already satisfied: plotly>=5.12.0 in /usr/local/lib/python3.13/dist-packages (from copulas>=0.12.1->sdv) (5.24.1)
Requirement already satisfied: scipy>=1.14.1 in /usr/local/lib/python3.13/dist-packages (from copulas>=0.12.1->sdv) (1.16.3)
Requirement already satisfied: torch>=2.6.0 in /usr/local/lib/python3.13/dist-packages (from ctgan>=0.11.1->sdv) (2.11.0+cpu)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<3,>=2.2.3->sdv) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<3,>=2.2.3->sdv) (2026.4)
Requirement already satisfied: scikit-learn>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from rdt<2,>=1.18.2->sdv) (1.6.1)
Collecting Faker!=37.11.0,>=17 (from rdt<2,>=1.18.2->sdv)
  Downloading faker-40.43.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly>=5.12.0->copulas>=0.12.1->sdv) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from plotly>=5.12.0->copulas>=0.12.1->sdv) (26.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.31->sdv) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.5.2->rdt<2,>=1.18.2->sdv) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.5.2->rdt<2,>=1.18.2->sdv) (3.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (4.0.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.6.0->ctgan>=0.11.1->sdv) (2025.12.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.6.0->ctgan>=0.11.1->sdv) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.6.0->ctgan>=0.11.1->sdv) (3.0.3)
Downloading sdv-1.38.5-py3-none-any.whl (215 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 215.6/215.6 kB 3.9 MB/s eta 0:00:00
Downloading boto3-1.43.111-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.0/140.0 kB 12.1 MB/s eta 0:00:00
Downloading botocore-1.43.111-py3-none-any.whl (16.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 71.2 MB/s eta 0:00:00
Downloading copulas-0.14.1-py3-none-any.whl (52 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.7/52.7 kB 4.6 MB/s eta 0:00:00
Downloading ctgan-0.12.1-py3-none-any.whl (25 kB)
Downloading deepecho-0.8.1-py3-none-any.whl (28 kB)
Downloading rdt-1.22.0-py3-none-any.whl (75 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.5/75.5 kB 5.9 MB/s eta 0:00:00
Downloading sdmetrics-0.32.0-py3-none-any.whl (259 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.9/259.9 kB 21.0 MB/s eta 0:00:00
Downloading faker-40.43.0-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 78.0 MB/s eta 0:00:00
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading s3transfer-0.19.2-py3-none-any.whl (90 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 kB 7.0 MB/s eta 0:00:00
Installing collected packages: jmespath, Faker, botocore, s3transfer, rdt, deepecho, copulas, sdmetrics, ctgan, boto3, sdv
Successfully installed Faker-40.43.0 boto3-1.43.111 botocore-1.43.111 copulas-0.14.1 ctgan-0.12.1 deepecho-0.8.1 jmespath-1.1.0 rdt-1.22.0 s3transfer-0.19.2 sdmetrics-0.32.0 sdv-1.38.5

In [34]:
import sdv

print(sdv.__version__)

1.38.5

In [35]:
df.columns.tolist()

['participant_id',
 'timestamp',
 'glucose_mg_dl',
 'heart_rate_bpm',
 'hrv_ms',
 'spo2_percent',
 'sleep_duration_hours',
 'activity_level',
 'steps',
 'sleep_quality',
 'device_type']

In [36]:
df.shape

(10000, 11)

In [37]:
id_cols = ["participant_id", "timestamp"]

ctgan_data = df.drop(columns=id_cols).copy()

ctgan_data.shape

(10000, 9)

In [38]:
ctgan_data.head()

,glucose_mg_dl,heart_rate_bpm,hrv_ms,spo2_percent,sleep_duration_hours,activity_level,steps,sleep_quality,device_type
0,107.840082,65.454512,54.239094,96.017807,5.500982,Low,252.0,Fair,Wearable_A
1,105.758855,63.699755,48.234028,95.728198,NaN,Low,37.0,NaN,Wearable_A
2,97.844208,74.428713,51.861775,97.958764,NaN,Moderate,1209.0,NaN,Wearable_C
3,112.451573,66.269009,39.164509,97.602378,NaN,Low,527.0,NaN,Wearable_A
4,121.005022,66.406237,48.133023,98.483996,NaN,Moderate,1246.0,NaN,Wearable_B

In [39]:
from sdv.metadata import Metadata

metadata = Metadata.detect_from_dataframe(
    data=ctgan_data
)

In [40]:
metadata

{
    "tables": {
        "table": {
            "columns": {
                "glucose_mg_dl": {
                    "sdtype": "numerical"
                },
                "heart_rate_bpm": {
                    "sdtype": "numerical"
                },
                "hrv_ms": {
                    "sdtype": "numerical"
                },
                "spo2_percent": {
                    "sdtype": "numerical"
                },
                "sleep_duration_hours": {
                    "sdtype": "numerical"
                },
                "activity_level": {
                    "sdtype": "categorical"
                },
                "steps": {
                    "sdtype": "numerical"
                },
                "sleep_quality": {
                    "sdtype": "categorical"
                },
                "device_type": {
                    "sdtype": "categorical"
                }
            }
        }
    },
    "relationships": [],
    "METADATA_SPEC_VERSION": "V1"
}

In [41]:
from sdv.single_table import CTGANSynthesizer

In [42]:
synthesizer = CTGANSynthesizer(
    metadata=metadata,     #Create the CTGAN
    epochs=100,
    verbose=True
)

/usr/local/lib/python3.13/dist-packages/sdv/single_table/base.py:139: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

In [43]:
synthesizer.fit(ctgan_data)

Gen. (-01.90) | Discrim. (+00.03): 100%|██████████| 100/100 [02:45<00:00,  1.65s/it]

In [44]:
synthetic_data = synthesizer.sample(
    num_rows=len(ctgan_data)
)

synthetic_data.head()

,glucose_mg_dl,heart_rate_bpm,hrv_ms,spo2_percent,sleep_duration_hours,activity_level,steps,sleep_quality,device_type
0,108.497707,83.853152,49.420044,99.323578,NaN,Low,NaN,NaN,Wearable_A
1,98.933710,75.917796,43.433923,97.840674,NaN,Moderate,1822.0,NaN,Wearable_A
2,133.635830,67.011046,47.792799,95.868678,NaN,Low,406.0,Poor,Wearable_A
3,111.682240,65.114440,38.851305,NaN,NaN,Low,169.0,Good,Wearable_A
4,107.961613,71.749170,44.888174,97.600542,NaN,Low,262.0,NaN,Wearable_A

In [45]:
synthetic_data.shape

(10000, 9)

In [46]:
synthetic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   glucose_mg_dl         9717 non-null   float64
 1   heart_rate_bpm        10000 non-null  float64
 2   hrv_ms                9802 non-null   float64
 3   spo2_percent          9876 non-null   float64
 4   sleep_duration_hours  3220 non-null   float64
 5   activity_level        10000 non-null  object
 6   steps                 9681 non-null   float64
 7   sleep_quality         4322 non-null   object
 8   device_type           10000 non-null  object
dtypes: float64(6), object(3)
memory usage: 703.3+ KB

In [47]:
# Compare real vs CTGAN synthetic: numerical distributions

numeric_cols = [
    "glucose_mg_dl",
    "heart_rate_bpm",
    "hrv_ms",
    "spo2_percent",
    "sleep_duration_hours",
    "steps"
]

ctgan_numeric_comparison = pd.DataFrame({
    "real_mean": ctgan_data[numeric_cols].mean(),
    "synthetic_mean": synthetic_data[numeric_cols].mean(),
    "real_std": ctgan_data[numeric_cols].std(),
    "synthetic_std": synthetic_data[numeric_cols].std()
}).round(2)

ctgan_numeric_comparison

                      real_mean  synthetic_mean  real_std  synthetic_std
glucose_mg_dl            106.25          106.50     13.79          12.46
heart_rate_bpm            72.73           74.37      6.74           7.26
hrv_ms                    46.05           45.00      8.86           8.84
spo2_percent              97.02           96.91      0.90           0.85
sleep_duration_hours       6.81            6.84      0.70           0.37
steps                    894.71         1125.51    974.64        1269.61

In [48]:
activity_compare_ctgan = pd.DataFrame({
    "real_%": ctgan_data["activity_level"].value_counts(normalize=True) * 100,
    "synthetic_%": synthetic_data["activity_level"].value_counts(normalize=True) * 100
}).round(2)

activity_compare_ctgan

                real_%  synthetic_%
activity_level
Low              57.73        57.26
Moderate         33.46        27.14
High              8.81        15.60

In [49]:
real_corr = ctgan_data[numeric_cols].corr()
synthetic_corr = synthetic_data[numeric_cols].corr()

corr_delta_ctgan = synthetic_corr - real_corr

corr_delta_ctgan.round(2)

,glucose_mg_dl,heart_rate_bpm,hrv_ms,spo2_percent,sleep_duration_hours,steps
glucose_mg_dl,0.00,-0.06,-0.09,0.02,0.05,-0.09
heart_rate_bpm,-0.06,0.00,-0.15,0.07,-0.03,0.06
hrv_ms,-0.09,-0.15,0.00,-0.10,0.01,-0.08
spo2_percent,0.02,0.07,-0.10,0.00,0.04,-0.01
sleep_duration_hours,0.05,-0.03,0.01,0.04,0.00,-0.04
steps,-0.09,0.06,-0.08,-0.01,-0.04,0.00

In [50]:
pairs = [
    ("heart_rate_bpm", "hrv_ms"),
    ("hrv_ms", "steps")
]

for col1, col2 in pairs:
    print(f"\n{col1} vs {col2}")
    print("Real:     ", round(ctgan_data[[col1, col2]].corr().iloc[0, 1], 2))
    print("Synthetic:", round(synthetic_data[[col1, col2]].corr().iloc[0, 1], 2))

heart_rate_bpm vs hrv_ms
Real:      -0.15
Synthetic: -0.3

hrv_ms vs steps
Real:      -0.21
Synthetic: -0.29

# **DAY 3**

In [51]:
# Day 3 — Fidelity: compare distribution quantiles

numeric_cols = [
    "glucose_mg_dl",
    "heart_rate_bpm",
    "hrv_ms",
    "spo2_percent",
    "sleep_duration_hours",
    "steps"
]

quantiles = [0.05, 0.25, 0.50, 0.75, 0.95]

for col in numeric_cols:
    print(f"\n{'='*60}")
    print(col)

    real_q = ctgan_data[col].quantile(quantiles)
    synthetic_q = synthetic_data[col].quantile(quantiles)

    comparison = pd.DataFrame({
        "real": real_q,
        "synthetic": synthetic_q,
        "difference": synthetic_q - real_q
    }).round(2)

    print(comparison)

============================================================
glucose_mg_dl
        real  synthetic  difference
0.05   84.57      87.08        2.50
0.25   96.80      98.40        1.59
0.50  105.77     105.83        0.06
0.75  115.06     114.12       -0.94
0.95  129.96     127.98       -1.98

============================================================
heart_rate_bpm
       real  synthetic  difference
0.05  62.14      63.55        1.41
0.25  67.85      68.63        0.78
0.50  72.33      73.74        1.42
0.75  77.34      80.27        2.93
0.95  84.34      86.22        1.88

============================================================
hrv_ms
       real  synthetic  difference
0.05  31.78      32.38        0.60
0.25  39.70      38.26       -1.44
0.50  45.96      43.41       -2.55
0.75  52.31      52.17       -0.14
0.95  60.96      60.53       -0.43

============================================================
spo2_percent
       real  synthetic  difference
0.05  95.62      95.77        0.14
0.25  96.37      96.25       -0.12
0.50  96.97      96.77       -0.19
0.75  97.62      97.48       -0.15
0.95  98.57      98.49       -0.08

============================================================
sleep_duration_hours
      real  synthetic  difference
0.05  5.65       6.20        0.55
0.25  6.36       6.81        0.45
0.50  6.81       6.82        0.01
0.75  7.27       6.82       -0.45
0.95  7.96       7.56       -0.40

============================================================
steps
        real  synthetic  difference
0.05    44.0      111.0        67.0
0.25   223.0      251.0        28.0
0.50   404.0      413.0         9.0
0.75  1417.0     1742.0       325.0
0.95  3048.0     4095.0      1047.0

In [52]:
from sklearn.model_selection import train_test_split    #Prepare the data
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

target = "activity_level"

features = [
    "glucose_mg_dl",
    "heart_rate_bpm",
    "hrv_ms",
    "spo2_percent",
    "sleep_duration_hours",
    "steps",
    "device_type"
]

# Real data
real_model_data = ctgan_data[features + [target]].copy()

# Synthetic data
synthetic_model_data = synthetic_data[features + [target]].copy()

X_real = real_model_data[features]
y_real = real_model_data[target]

X_synthetic = synthetic_model_data[features]
y_synthetic = synthetic_model_data[target]

In [53]:
X_real_train, X_real_test, y_real_train, y_real_test = train_test_split( #Split the real data
    X_real,
    y_real,
    test_size=0.20,
    random_state=42,
    stratify=y_real
)

print("Real training rows:", len(X_real_train))
print("Real test rows:", len(X_real_test))

Real training rows: 8000
Real test rows: 2000

In [55]:
numeric_features = [
    "glucose_mg_dl",
    "heart_rate_bpm",
    "hrv_ms",
    "spo2_percent",
    "sleep_duration_hours",
    "steps"
]

categorical_features = [
    "device_type"
]
numeric_pipeline = Pipeline([          #Build the model
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numeric_features),
    ("cat", categorical_pipeline, categorical_features)
])

model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ))
])

In [56]:
# Train ONLY on synthetic data
model.fit(X_synthetic, y_synthetic)

# Test ONLY on unseen real data
y_pred = model.predict(X_real_test)

tstr_accuracy = accuracy_score(y_real_test, y_pred)

print("TSTR Accuracy:", round(tstr_accuracy, 3))

print("\nClassification Report:")
print(classification_report(y_real_test, y_pred))

TSTR Accuracy: 0.836

Classification Report:
              precision    recall  f1-score   support

        High       0.82      0.45      0.58       176
         Low       0.84      1.00      0.91      1155
    Moderate       0.84      0.66      0.74       669

    accuracy                           0.84      2000
   macro avg       0.83      0.70      0.74      2000
weighted avg       0.84      0.84      0.82      2000

In [57]:
real_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ))
])

# Train on real training data
real_model.fit(X_real_train, y_real_train)

# Test on the same real test data
y_real_pred = real_model.predict(X_real_test)

real_accuracy = accuracy_score(y_real_test, y_real_pred)

print("Real → Real Accuracy:", round(real_accuracy, 3))
print("Synthetic → Real Accuracy:", round(tstr_accuracy, 3))

Real → Real Accuracy: 0.947
Synthetic → Real Accuracy: 0.836

In [58]:
# Check whether synthetic rows exactly match real rows i.e, Privacy Check 1 — Exact duplicate rows

real_check = ctgan_data.reset_index(drop=True)
synthetic_check = synthetic_data.reset_index(drop=True)

# Convert rows to tuples so we can compare them
real_rows = set(real_check.astype(str).apply(tuple, axis=1))

exact_matches = synthetic_check.astype(str).apply(
    tuple, axis=1
).isin(real_rows)

print("Synthetic rows:", len(synthetic_check))
print("Exact matches:", exact_matches.sum())
print(
    "Exact match percentage:",
    round(exact_matches.mean() * 100, 2),
    "%"
)

Synthetic rows: 10000
Exact matches: 0
Exact match percentage: 0.0 %

In [59]:
from sklearn.impute import SimpleImputer          #Privacy Check 2 — Check for very similar records
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors

privacy_numeric = [
    "glucose_mg_dl",
    "heart_rate_bpm",
    "hrv_ms",
    "spo2_percent",
    "sleep_duration_hours",
    "steps"
]

real_numeric = ctgan_data[privacy_numeric]
synthetic_numeric = synthetic_data[privacy_numeric]

# Fill missing values using real-data medians
imputer = SimpleImputer(strategy="median")

real_imputed = imputer.fit_transform(real_numeric)
synthetic_imputed = imputer.transform(synthetic_numeric)

# Put variables on comparable scales
scaler = StandardScaler()

real_scaled = scaler.fit_transform(real_imputed)
synthetic_scaled = scaler.transform(synthetic_imputed)

# Find nearest real record for every synthetic record
nn = NearestNeighbors(n_neighbors=1)
nn.fit(real_scaled)

distances, indices = nn.kneighbors(synthetic_scaled)

nearest_distances = distances[:, 0]

print("Minimum distance:", round(nearest_distances.min(), 3))
print("Median distance:", round(float(__import__("numpy").median(nearest_distances)), 3))
print("5th percentile:", round(float(__import__("numpy").percentile(nearest_distances, 5)), 3))
print("95th percentile:", round(float(__import__("numpy").percentile(nearest_distances, 95)), 3))

Minimum distance: 0.061
Median distance: 0.417
5th percentile: 0.212
95th percentile: 0.88